sudo: required
dist: xenial

language: cpp
compiler: gcc

# whitelisted packages can be obtained quickly without downloading
# doxygen is out of date, tho so we download its binaries
addons:
  apt:
    packages:
      - cmake
      - build-essential
      - cppcheck
      - git
      - make
      - binutils-dev
      - libiberty-dev
      - openssl
      - libssl-dev
      - zlib1g-dev
      - zip
      - unzip

git:
  depth: 1

before_install:
  - sudo apt-get -qq install mariadb-server libace-6.* libace-dev
  - if [[ $TRAVIS_PULL_REQUEST == 'true' ]]; then exit; fi
  
install:
  - cd ..
  - git clone --depth=1 --branch=master https://github.com/talamortis/OregonCore.git oregoncore
  - mv OregonCore-Modules/modules_scripts/* oregoncore/modules/
  - cd oregoncore
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_C_COMPILER="gcc" -DCMAKE_CXX_COMPILER="g++" -DSERVERS=1 -DTOOLS=1 -DSCRIPTS=1 -DWITH_DOCS=1 -DWITH_WARNINGS=0 -DWITH_COREDEBUG=0
  - make -j2

script:
  - cd /home/travis/build/talamortis/oregoncore/sql
  - sudo mysql -u root --password='' < create/create_mysql.sql
  - mysql -u oregon -poregon realmd < base/realmd.sql
  - mysql -u oregon -poregon characters < base/characters.sql
  # mysql -u oregon -poregon world < base/world.sql
  - curl -L --retry 3 -o database_06_11_2020.zip https://github.com/talamortis/OregonCore/releases/download/v1.0/database_06_11_2020.zip
  - unzip database_06_11_2020.zip
  - mysql -u oregon -poregon world < database_06_11_2020.sql
  - cat /home/travis/build/talamortis/oregoncore/sql/updates/realmd/*.sql | mysql -u oregon -poregon realmd
  - cat /home/travis/build/talamortis/oregoncore/sql/updates/characters/*.sql | mysql -u oregon -poregon characters
  - cat /home/travis/build/talamortis/oregoncore/sql/updates/world/*.sql | mysql -u oregon -poregon world